# Generated by Django 4.2.7 on 2023-11-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apipractise', '0003_rename_product_warranty_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warranty',
            old_name='product_name',
            new_name='product_warranty',
        ),
    ]
