# Generated by Django 4.2.7 on 2023-11-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipractise', '0004_rename_product_name_warranty_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='warranty_provider',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
