# Generated by Django 4.2.7 on 2023-11-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipractise', '0005_warranty_warranty_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='warranty_provider',
            field=models.CharField(default='Jumia', max_length=20),
        ),
    ]
