# Generated by Django 4.2.7 on 2023-11-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apipractise', '0006_alter_warranty_warranty_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='products_for_customer',
        ),
    ]
