# Generated by Django 4.2.7 on 2023-11-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipractise', '0007_rename_customer_product_products_for_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='products_for_customer',
            field=models.ManyToManyField(related_name='customer_products', to='apipractise.customer'),
        ),
    ]
